image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

build:
  stage: build
  script:
    - docker build -t hiteshmondaldocker/watchtube:latest .

push:
  stage: push
  script:
    - docker push hiteshmondaldocker/watchtube:latest
  only:
    - main

deploy:
  stage: deploy
  script:
    - apk add --no-cache openssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
    - ssh $SERVER_USER@$SERVER_IP "docker pull hiteshmondaldocker/watchtube:latest && docker compose -f /path/to/your/docker-compose.yml up -d"
  only:
    - main
