version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app:cached
    environment:
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
    stdin_open: true
    tty: true
